services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: ./server
      dockerfile: dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.docker
    command: sh -c "npx prisma migrate deploy && node dist/index.mjs"
    ports:
      - "${PORT:-4750}:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  pgdata: